name: Workshop 0 Workflow

on: [workflow_dispatch]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: [AutoTest]
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1